import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr';

export const translations = {
  en: {
    // Auth
    loginTitle: 'Log in to your account',
    loginSubtitle: 'Welcome back to the B2B portal',
    registerTitle: 'Register your business',
    registerSubtitle: 'Join our B2B network today',
    businessCode: 'Business Code',
    businessCodePlaceholder: 'e.g., SCASAAUTO28CASA',
    password: 'Password',
    loginBtn: 'Log In',
    newHere: 'New here? Register your business.',
    ownerName: 'Owner Name',
    role: 'Role',
    buyer: 'Buyer',
    seller: 'Seller',
    businessName: 'Business Name',
    phone: 'Phone Number',
    email: 'Email Address',
    address: 'Address',
    uploadRC: 'Upload Registre de Commerce (RC)',
    confirmPassword: 'Confirm Password',
    createAccountBtn: 'Create Account',
    alreadyRegistered: 'Already registered? Log In here.',
    passwordsDoNotMatch: 'Passwords do not match',
    uploadRCError: 'Please upload your Registre de Commerce (RC)',
    businessCodeNotFound: 'Business Code not found',
    loginError: 'An error occurred during login.',
    registerError: 'An error occurred during registration.',
    accountCreated: 'Account created! Please check your email to verify your account before logging in.',
    invalidCredentials: 'Invalid login credentials',

    // App Header & Profile
    dashboard: 'Dashboard',
    myInventory: 'My Inventory',
    orderLedger: 'Order Ledger',
    preferences: 'Preferences',
    helpSupport: 'Help & Support',
    requestCredentialChange: 'Request Credential Change',
    logOut: 'Log Out',
    staffManagement: 'Staff Management',
    addNewStaff: 'Add New Staff',
    fullName: 'Full Name',
    userId: 'User ID',
    admin: 'Admin',
    manager: 'Manager',
    staff: 'Staff',
    inactive: 'Inactive',
    updateBusinessCredentials: 'Update Business Credentials',
    credentialChangeBody1: 'For security and billing purposes, core business credentials cannot be changed automatically. Modifying your business name or address requires the generation of a new Business Code.',
    credentialChangeBody2: 'Please contact our Customer Support team to process this change safely.',
    cancel: 'Cancel',
    contactSupport: 'Contact Support',

    // App Home
    appTitle: 'AutoGlass Portal',
    runningDemoMode: 'Running in Demo Mode',
    demoModeDesc: 'Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to connect to your live database.',
    smartScanner: 'Smart Scanner',
    addToInventory: 'Add to Inventory (+)',
    soldOffline: 'Sold Offline (-)',
    scanBarcodePlaceholder: 'Scan or enter barcode...',
    scanBtn: 'Scan',
    inventoryManagement: 'Inventory Management',
    searchInventory: 'Search inventory...',
    addItem: 'Add Item',
    sku: 'SKU',
    vehicle: 'Vehicle',
    manufacturer: 'Manufacturer',
    position: 'Position',
    qty: 'Qty',
    price: 'Price',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    activeOrders: 'Active Orders',
    orderId: 'Order ID',
    status: 'Status',
    noOrders: 'No active orders.',
    noInventory: 'No inventory items found.',
    saveChanges: 'Save Changes',
    editItem: 'Edit Item',
    pendingOrders: 'Pending Orders',
    loadingOrders: 'Loading orders...',
    noPendingOrders: 'No pending orders.',
    uploadBonDeCommande: 'Upload Bon de Commande',
    activeInventory: 'Active Inventory',
    searchCatalog: 'Search catalog...',
    loadingCatalog: 'Loading catalog...',
    noActiveInventory: 'No active inventory found.',
    editVehicle: 'Edit Vehicle',
    unitPrice: 'Unit Price',
    moveStock: 'Move Stock to Different Vehicle',
    movingInventory: 'Moving Inventory:',
    windshields: 'Windshields',
    currentlyAssignedTo: 'Currently assigned to:',
    brand: 'Brand',
    selectBrand: 'Select Brand',
    otherNotInList: '[ + Other / Not in List ]',
    model: 'Model',
    selectModel: 'Select Model',
    yearRange: 'Year Range',
    selectYear: 'Select Year',
    customBrand: 'Custom Brand',
    customModel: 'Custom Model',
    customYear: 'Custom Year',
    selectManufacturer: 'Select Manufacturer',
    glassPosition: 'Glass Position',
    selectPosition: 'Select Position',
    customManufacturerName: 'Custom Manufacturer Name',
    customPositionName: 'Custom Position Name',
    quantity: 'Quantity',
    unitPriceMad: 'Unit Price (MAD)',
    salePriceMad: 'Sale Price (MAD)',
    executeInsert: 'Execute Insert',
    executeUpdate: 'Execute Update',
    multipleMatches: 'Multiple matches found for this barcode. Select the correct vehicle:',
    selectVehicle: 'Select Vehicle',
    recognizedPart: 'Recognized Part (Verify Details):',
    newPartDetected: 'New Part Detected. Please categorize:',
    incorrectVehicle: 'Incorrect Vehicle? Change Match',
    ensureSpelling: '⚠️ Please ensure spelling is correct before saving.',
    ensureMfgSpelling: '⚠️ Please ensure manufacturer spelling is correct.',
    ensurePosSpelling: '⚠️ Please ensure position spelling is correct.',
    scanning: 'Scanning...',
    usbReady: 'USB Ready',
    unknownPosition: 'Unknown Position',
    unknown: 'Unknown',
    posFrontWindshield: 'Front Windshield',
    posRearWindow: 'Rear Window',
    posFrontLeftDoor: 'Front Left Door',
    posFrontRightDoor: 'Front Right Door',
    posRearLeftDoor: 'Rear Left Door',
    posRearRightDoor: 'Rear Right Door',
    posQuarterGlass: 'Quarter Glass',
    posSunroof: 'Sunroof',
    posOther: 'Other',
    deleteItem: 'Delete Item',
    deleteConfirmTitle: 'Delete Inventory Item',
    deleteConfirmBody: 'Are you sure you want to permanently delete this item from your inventory? This action cannot be undone.',
    confirmDelete: 'Confirm Delete',
    itemDeletedSuccess: 'Item deleted successfully.',
    orderDate: 'Order Date',
    buyerName: 'Buyer Name',
    totalPrice: 'Total Price',
    viewPO: 'View BDC',
    accept: 'Accept',
    reject: 'Reject',
    prepareForDelivery: 'Prepare for Delivery',
    markAsCompleted: 'Mark as Completed',
    orderAccepted: 'Order accepted successfully.',
    orderRejected: 'Order rejected successfully.',
    orderPreparing: 'Order is being prepared for delivery.',
    orderCompleted: 'Order marked as completed.',
    errorUpdatingOrder: 'Error updating order status.',
    officeDashboard: 'Office Dashboard',
    actionRequired: 'Action Required',
    urgent: 'Urgent',
    inProgress: 'In Progress',
    deleteError: "An error occurred while deleting the item.",
    active: 'Active',
    orderHistory: 'Order History',
    myTransactions: 'My Transactions',
    cancelOrderTitle: 'Cancel this Order?',
    cancelOrderBody: 'Are you sure you want to cancel this order? The buyer will be notified.',
    goBack: 'Go Back',
    confirmCancellation: 'Confirm Cancellation',
    orderCancelledSuccess: 'Order cancelled successfully.',
    errorCancellingOrder: 'Error cancelling order.',
    refCode: 'REF',
    viewRefPhoto: 'View Reference Photo',
  },
  fr: {
    // Auth
    loginTitle: 'Connectez-vous à votre compte',
    loginSubtitle: 'Bon retour sur le portail B2B',
    registerTitle: 'Enregistrez votre entreprise',
    registerSubtitle: 'Rejoignez notre réseau B2B aujourd\'hui',
    businessCode: 'Code d\'entreprise',
    businessCodePlaceholder: 'ex: SCASAAUTO28CASA',
    password: 'Mot de passe',
    loginBtn: 'Se connecter',
    newHere: 'Nouveau ici ? Enregistrez votre entreprise.',
    ownerName: 'Nom du propriétaire',
    role: 'Rôle',
    buyer: 'Acheteur',
    seller: 'Vendeur',
    businessName: 'Nom de l\'entreprise',
    phone: 'Numéro de téléphone',
    email: 'Adresse e-mail',
    address: 'Adresse',
    uploadRC: 'Télécharger le Registre de Commerce (RC)',
    confirmPassword: 'Confirmer le mot de passe',
    createAccountBtn: 'Créer un compte',
    alreadyRegistered: 'Déjà inscrit ? Connectez-vous ici.',
    passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
    uploadRCError: 'Veuillez télécharger votre Registre de Commerce (RC)',
    businessCodeNotFound: 'Code d\'entreprise introuvable',
    loginError: 'Une erreur est survenue lors de la connexion.',
    registerError: 'Une erreur est survenue lors de l\'inscription.',
    accountCreated: 'Compte créé ! Veuillez vérifier votre e-mail pour valider votre compte avant de vous connecter.',
    invalidCredentials: 'Identifiants invalides',

    // App Header & Profile
    dashboard: 'Tableau de bord',
    myInventory: 'Mon Inventaire',
    orderLedger: 'Registre des commandes',
    preferences: 'Préférences',
    helpSupport: 'Aide et Support',
    requestCredentialChange: 'Demande de modification des identifiants',
    logOut: 'Se déconnecter',
    staffManagement: 'Gestion du personnel',
    addNewStaff: 'Ajouter du personnel',
    fullName: 'Nom complet',
    userId: 'ID Utilisateur',
    admin: 'Admin',
    manager: 'Manager',
    staff: 'Personnel',
    inactive: 'Inactif',
    updateBusinessCredentials: 'Mettre à jour les identifiants',
    credentialChangeBody1: 'Pour des raisons de sécurité et de facturation, les identifiants principaux de l\'entreprise ne peuvent pas être modifiés automatiquement. La modification du nom ou de l\'adresse de votre entreprise nécessite la génération d\'un nouveau code d\'entreprise.',
    credentialChangeBody2: 'Veuillez contacter notre équipe d\'assistance client pour traiter ce changement en toute sécurité.',
    cancel: 'Annuler',
    contactSupport: 'Contacter le support',

    // App Home
    appTitle: 'Portail AutoGlass',
    runningDemoMode: 'Mode Démo',
    demoModeDesc: 'Définissez VITE_SUPABASE_URL et VITE_SUPABASE_ANON_KEY pour vous connecter à votre base de données.',
    smartScanner: 'Scanner Intelligent',
    addToInventory: 'Ajouter à l\'inventaire (+)',
    soldOffline: 'Vendu hors ligne (-)',
    scanBarcodePlaceholder: 'Scanner ou entrer le code-barres...',
    scanBtn: 'Scanner',
    inventoryManagement: 'Gestion de l\'inventaire',
    searchInventory: 'Rechercher dans l\'inventaire...',
    addItem: 'Ajouter un article',
    sku: 'SKU',
    vehicle: 'Véhicule',
    manufacturer: 'Fabricant',
    position: 'Position',
    qty: 'Qté',
    price: 'Prix',
    actions: 'Actions',
    edit: 'Modifier',
    delete: 'Supprimer',
    activeOrders: 'Commandes Actives',
    orderId: 'ID Commande',
    status: 'Statut',
    noOrders: 'Aucune commande active.',
    noInventory: 'Aucun article trouvé dans l\'inventaire.',
    saveChanges: 'Enregistrer les modifications',
    editItem: 'Modifier l\'article',
    pendingOrders: 'Commandes en attente',
    loadingOrders: 'Chargement des commandes...',
    noPendingOrders: 'Aucune commande en attente.',
    uploadBonDeCommande: 'Télécharger le Bon de Commande',
    activeInventory: 'Inventaire Actif',
    searchCatalog: 'Rechercher dans le catalogue...',
    loadingCatalog: 'Chargement du catalogue...',
    noActiveInventory: 'Aucun inventaire actif trouvé.',
    editVehicle: 'Modifier le véhicule',
    unitPrice: 'Prix unitaire',
    moveStock: 'Déplacer le stock vers un autre véhicule',
    movingInventory: 'Déplacement de l\'inventaire :',
    windshields: 'Pare-brises',
    currentlyAssignedTo: 'Actuellement assigné à :',
    brand: 'MARQUE',
    selectBrand: 'Sélectionner une marque',
    otherNotInList: '[ + Autre / Pas dans la liste ]',
    model: 'MODÈLE',
    selectModel: 'Sélectionner un modèle',
    yearRange: 'ANNÉES',
    selectYear: 'Sélectionner une année',
    customBrand: 'Marque personnalisée',
    customModel: 'Modèle personnalisé',
    customYear: 'Année personnalisée',
    selectManufacturer: 'Sélectionner un fabricant',
    glassPosition: 'POSITION DU VITRAGE',
    selectPosition: 'Sélectionner une position',
    customManufacturerName: 'Nom du fabricant personnalisé',
    customPositionName: 'Nom de la position personnalisée',
    quantity: 'QUANTITÉ',
    unitPriceMad: 'PRIX UNITAIRE (MAD)',
    salePriceMad: 'PRIX DE VENTE (MAD)',
    executeInsert: 'Exécuter l\'insertion',
    executeUpdate: 'Exécuter la mise à jour',
    multipleMatches: 'Plusieurs correspondances trouvées pour ce code-barres. Sélectionnez le bon véhicule :',
    selectVehicle: 'Sélectionner le véhicule',
    recognizedPart: 'Pièce reconnue (Vérifiez les détails) :',
    newPartDetected: 'Nouvelle pièce détectée. Veuillez catégoriser :',
    incorrectVehicle: 'Véhicule incorrect ? Changer la correspondance',
    ensureSpelling: '⚠️ Veuillez vérifier l\'orthographe avant d\'enregistrer.',
    ensureMfgSpelling: '⚠️ Veuillez vérifier l\'orthographe du fabricant.',
    ensurePosSpelling: '⚠️ Veuillez vérifier l\'orthographe de la position.',
    scanning: 'Numérisation...',
    usbReady: 'Prêt pour USB',
    unknownPosition: 'Position inconnue',
    unknown: 'Inconnu',
    posFrontWindshield: 'Pare-brise avant',
    posRearWindow: 'Lunette arrière',
    posFrontLeftDoor: 'Vitre porte avant gauche',
    posFrontRightDoor: 'Vitre porte avant droite',
    posRearLeftDoor: 'Vitre porte arrière gauche',
    posRearRightDoor: 'Vitre porte arrière droite',
    posQuarterGlass: 'Vitre de custode',
    posSunroof: 'Toit ouvrant',
    posOther: 'Autre',
    deleteItem: 'Supprimer l\'article',
    deleteConfirmTitle: 'Supprimer l\'article',
    deleteConfirmBody: 'Êtes-vous sûr de vouloir supprimer définitivement cet article de votre inventaire ? Cette action est irréversible.',
    confirmDelete: 'Confirmer la suppression',
    itemDeletedSuccess: 'Article supprimé avec succès.',
    orderDate: 'Date de commande',
    buyerName: 'Nom de l\'acheteur',
    totalPrice: 'Prix total',
    viewPO: 'Voir BC',
    accept: 'Accepter',
    reject: 'Rejeter',
    prepareForDelivery: 'Préparer pour la livraison',
    markAsCompleted: 'Marquer comme terminé',
    orderAccepted: 'Commande acceptée avec succès.',
    orderRejected: 'Commande rejetée avec succès.',
    orderPreparing: 'La commande est en cours de préparation pour la livraison.',
    orderCompleted: 'Commande marquée comme terminée.',
    errorUpdatingOrder: 'Erreur lors de la mise à jour du statut de la commande.',
    officeDashboard: 'Tableau de bord Bureau',
    actionRequired: 'Action requise',
    urgent: 'Urgent',
    inProgress: 'En cours',
    deleteError: "Une erreur s'est produite lors de la suppression de l'élément.",
    active: 'Active',
    orderHistory: 'Historique des commandes',
    myTransactions: 'Mes transactions',
    cancelOrderTitle: 'Annuler cette commande ?',
    cancelOrderBody: 'Êtes-vous sûr de vouloir annuler cette commande ? L\'acheteur sera notifié.',
    goBack: 'Retour',
    confirmCancellation: 'Confirmer l\'annulation',
    orderCancelledSuccess: 'Commande annulée avec succès.',
    errorCancellingOrder: 'Erreur lors de l\'annulation de la commande.',
    refCode: 'RÉF',
    viewRefPhoto: 'Voir la photo de référence',
    
  }
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: typeof translations.en;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>('en');

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
